#+STARTUP: showall
#+OPTIONS: toc:nil 


* The very basics
** Notes
Sounds are vibrations in air that we can hear. Slower vibrations give lower sounds, faster
vibrations give higher sounds and good vibrations give goosebumps. Let's call these vibrations 
the *pitch*. Pitch is measured in hertz or vibrations per second.

*** TODO Illustration of vibrating string or speaker

Talking about pitch isn't very intuitive so we took certain pitches and gave them names. For
example 440 hertz is generally used for a *note* called "A". 

Notes have different relationships with each other. Some are friendly and sound *harmonious*, 
some might clash with each other and sound *discordant*. We will talk a lot about the 
distance between notes so let's call this the *interval* between two
notes. It turns out that identifying the actual notes, whilst helpful, is not as powerful as 
understanding how notes relate to each other.

*** TODO Illustrate two notes on an instrument and the same two notes on a score

** Our first two important intervals
Our ears can clearly tell when one note is vibrating twice as fast as a lower note. For reasons 
that will become clear shortly, we call this distance or interval between notes an *octave*.
Octaves are quite far apart, so we need to chop them up into smaller intervals. It turns out our 
ears are very sensitive to how we do this. The majority of music today is made by chopping up 
the distance between two octaves into 12 parts called *semitones* (or half-steps).
A distance of two semitones is called a *tone* or whole tone (or whole-step).

You can see on a guitar neck, the 12th fret will give a note one octave higher than the open 
string. Each fret is a semitone. You can also see a repeating pattern of white and black keys 
on a piano which are the 12 semitones between the octaves. Each key is a semitone apart.

*** TODO Guitar neck and piano keyboard illustration

** Summary so far
Now we have *notes* and *interval* between any two notes. We have *octaves* divided into
*semitones* and *tones*. We know that these were not arbitrary choices but are a language devised
to describe this phenomena of how notes interact to make *music*

* Scales
** Using intervals to define scales
We found there are groupings of notes that have interesting relationships with each other. We 
can define these groups by their intervals and we call these groups *scales*. An important scale 
is the *Major scale*, which has 7 notes and can be played as follows:
#+ATTR_HTML: :border 0 :rules all :frame none
 | tone | tone | semitone | tone | tone | tone | semitone |
We can write this shorter as *TTSTTTS*.

You should try playing it at this point. Pick any note on a guitar or key on a piano and 
then simply count them out (pick a note and stay on the same string for guitar or ensure you count
all notes black and white on a keyboard):
  - Play a random first note
  - go up 1 tone (or 2 semitones, 2 frets, 2 keys) to the 2nd note,
  - 1 tone (or 2 semitones) again to the 3rd note,
  - 1 semitone to the 4th note,
  - 1 tone to the 5th note,
  - 1 tone to the 6th note,
  - 1 tone to the 7th note,
  - 1 semitone takes us to the next octave (or 8th or 8ve).

*** TODO Illustration of playing this on a guitar neck and keyboard

Hopefully you now see why octaves have their name, based on the major scale, it takes 8 
intervals to get from one octave to the next. Did it sound right to your ears? You should have 
played a major scale but we haven't yet named any notes!

You will understand a lot more about music if you think in intervals, with the degrees of the 
scale as 1st, 2nd, 3rd, 4th, 5th, 6th, 7th, 8th (and keep going ... 9th, 11th, 13th, etc). We 
will use this a lot.

** Keys and scales
First let's name the 12 semitones. Some have letters and some are considered sharp (\sharp) or 
flat (\flat). Using sharps, we can write the 12 semitones out like this:
#+ATTR_HTML: :border 0 :rules all :frame none
  | 1 |                2 | 3 |                4 | 5 | 6 |                7 | 8 |                9 | 10 |               11 | 12 |
  |---+------------------+---+------------------+---+---+------------------+---+------------------+----+------------------+----|
  | C | C\sharp / D\flat | D | D\sharp / E\flat | E | F | F\sharp / G\flat | G | G\sharp / A\flat |  A | A\sharp / B\flat |  B |
There is no extra note between E and F, nor between B and C. Unfortunately these extra notes may have 
two (or more!!) names because the \flat or \sharp is not really a name but an instruction to the
musician to sharpen or flatten by a semitone. So \sharp{}\sharp{} means to sharpen by a whole tone. In 
between C and D is a note that is either C\sharp [see-Sharp] or D\flat [dee-flat]. This is 
actually to simplify things. We'll begin to see how, as we progress.

Let us now try naming some notes in the major scale and see what happens. Check these scales using 
the table of named semitones above and the TTSTTTS pattern.
#+ATTR_HTML: :border 0 :rules all :frame none
  | Degree | C Major | G Major |
  |--------+---------+---------|
  | 1st    | C       | G       |
  | 2nd    | D       | A       |
  | 3rd    | E       | B       |
  | 4th    | F       | C       |
  | 5th    | G       | D       |
  | 6th    | A       | E       |
  | 7th    | B       | F\sharp |
  | 8th    | C       | G       |

To make things simpler, we want to have an A B C D E F and G in every major scale. This is why, in the 
G Major example above, we choose to use the F\sharp and not G\flat. It is much clearer to 
have A B C D E F\sharp G than with two G's in A B C D E G\flat G.

Now we can talk about music being in a *key*, for example the music may centre around G and
use mostly notes from the major scale, so it's key is G Major. When we say key of G Major we 
are saying the *root* or *tonic* or *tonal centre* is G and we determine the rest of the notes 
using the interval pattern TTSTTTS.

** All major scales
Using everything we've learned so far, we can now construct every major scale. There will be one 
for each of our 12 notes. You should try doing this yourself. Start with the easy one, C, but don't 
make the next one D, rather choose the 5th interval of C for the next key (which is G). We'll see why
we did this in a moment. Here's a starter for you:
#+ATTR_HTML: :border 0 :rules all :frame none
  | Degree | C | G       | D |   |   |   |   |   |   |
  |--------+---+---------+---+---+---+---+---+---+---|
  | 1st    | C | G       |   |   |   |   |   |   |   |
  | 2nd    | D | A       |   |   |   |   |   |   |   |
  | 3rd    | E | B       |   |   |   |   |   |   |   |
  | 4th    | F | C       |   |   |   |   |   |   |   |
  | *5th*  | G | D       |   |   |   |   |   |   |   |
  | 6th    | A | E       |   |   |   |   |   |   |   |
  | 7th    | B | F\sharp |   |   |   |   |   |   |   |

When we get to F\sharp things start getting a bit tricky. We end up with needing an E\sharp. Remember 
the \sharp is an instruction to sharpen the E by one semintone, which correctly gives F, so E\sharp
is perfectly valid. Carrying on the C\sharp scale now has E\sharp and B\sharp. Once we get to 
G\sharp we're really in trouble, it has become impossible to support our desire to have ABCDEFG in 
each scale unless we write F\sharp{}\sharp{}. 
#+ATTR_HTML: :border 0 :rules all :frame none
  | Degree | C | G       | D       | A       | E       | B       | F\sharp     | C\sharp / D\flat | G\sharp / A\flat    |
  |--------+---+---------+---------+---------+---------+---------+-------------+------------------+---------------------|
  | 1st    | C | G       | D       | A       | E       | B       | F\sharp     | C\sharp          | G\sharp             |
  | 2nd    | D | A       | E       | B       | F\sharp | C\sharp | G\sharp     | D\sharp          | A\sharp             |
  | 3rd    | E | B       | F\sharp | C\sharp | G\sharp | D\sharp | A\sharp     | E\sharp (F)      | B\sharp (C)         |
  | 4th    | F | C       | G       | D       | A       | E       | B           | F\sharp          | C\sharp             |
  | *5th*  | G | D       | A       | E       | B       | F\sharp | C\sharp     | G\sharp          | D\sharp             |
  | 6th    | A | E       | B       | F\sharp | C\sharp | G\sharp | D\sharp     | A\sharp          | E\sharp(F)          |
  | 7th    | B | F       | C\sharp | G\sharp | D\sharp | A\sharp | E\sharp (F) | B\sharp (C)      | *F\sharp{}\sharp{}* |
  | 8th    | C | F\sharp | D       | A       | E       | B       | F\sharp     | C\sharp          | G\sharp             |

Whilst it is actually valid to write F\sharp{}\sharp{}, by using flats, we can make things much clearer.
#+ATTR_HTML: :border 0 :rules all :frame none
  | Degree | C\sharp / D\flat | G\sharp / A\flat | D\sharp / E\flat | A\sharp / B\flat | F      | C | G       | D       | A       | E       | B       | F\sharp / G\flat |
  |--------+------------------+------------------+------------------+------------------+--------+---+---------+---------+---------+---------+---------+------------------|
  | 1st    | D\flat           | A\flat           | E\flat           | B\flat           | F      | C | G       | D       | A       | E       | B       | F\sharp          |
  | 2nd    | E\flat           | B\flat           | F                | C                | G      | D | A       | E       | B       | F\sharp | C\sharp | G\sharp          |
  | 3rd    | F                | C                | G                | D                | A      | E | B       | F\sharp | C\sharp | G\sharp | D\sharp | A\sharp          |
  | <- 4th | G\flat           | D\flat           | A\flat           | E\flat           | B\flat | F | C       | G       | D       | A       | E       | B                |
  | 5th -> | A\flat           | E\flat           | B\flat           | F                | C      | G | D       | A       | E       | B       | F\sharp | C\sharp          |
  | 6th    | B\flat           | F                | C                | G                | D      | A | E       | B       | F\sharp | C\sharp | G\sharp | D\sharp          |
  | 7th    | C                | G                | D                | A                | E      | B | F       | C\sharp | G\sharp | D\sharp | A\sharp | E\sharp[F]       |
  | 8th    | D\flat           | A\flat           | E\flat           | B\flat           | F      | C | F\sharp | D       | A       | E       | B       | F\sharp          |
You should be able to see that the 5th of F\sharp is C\sharp or D\flat and so loops back to 
the 1st column. This circular reference forms part of the circle of 5ths which was invented by 
Pythagoras. From left to right you choose the 5th to get the next scale and right to left you 
choose the 4th. 

Let's reformat that table so you can you see how the flats and sharps build up as well as other 
patterns between the keys. Columns are orderd in 5ths and rows are ordered in 5ths.
#+ATTR_HTML: :border 0 :rules all :frame none
  | D\flat | A\flat | E\flat | B\flat | F      | C | G       | D       | A       | E       | B       | F\sharp    |
  |--------+--------+--------+--------+--------+---+---------+---------+---------+---------+---------+------------|
  | F      | F      | F      | F      | F      | F | F\sharp | F\sharp | F\sharp | F\sharp | F\sharp | F\sharp    |
  | C      | C      | C      | C      | C      | C | C       | C\sharp | C\sharp | C\sharp | C\sharp | C\sharp    |
  | G\flat | G      | G      | G      | G      | G | G       | G       | G\sharp | G\sharp | G\sharp | G\sharp    |
  | D\flat | D\flat | D      | D      | D      | D | D       | D       | D       | D\sharp | D\sharp | D\sharp    |
  | A\flat | A\flat | A\flat | A      | A      | A | A       | A       | A       | A       | A\sharp | A\sharp    |
  | E\flat | E\flat | E\flat | E\flat | E      | E | E       | E       | E       | E       | E       | E\sharp[F] |
  | B\flat | B\flat | B\flat | B\flat | B\flat | B | B       | B       | B       | B       | B       | B          |

** Minor scales
Because you know all the major scales, and you understand intervals, you know the *minor scales* as 
well. All you need are the rules on how to find them. One way to find a minor scale is to go left 
by 3 intervals from the root of the major scale. Start there and play all the notes from the major 
scale, you have found the *natural minor* or *relative minor*. 
#+ATTR_HTML: :border 0 :rules all :frame none
  | Major | D\flat    | A\flat | E\flat | B\flat | F  | C  | G  | D  | A          | E          | B          | F\sharp    |
  | Minor | B\flat{}m | Fm     | Cm     | Gm     | Dm | Am | Em | Bm | F\sharp{}m | C\sharp{}m | G\sharp{}m | D\sharp{}m |
Another way is looking at the pattern we use to construct a scale. Take the major TTSTTTS and 
shift it 3 to the right you get TSTTSTT. This is the same as going three intervals to the left. Yet 
another way to look at this is that the relative minor always starts on the 6th degree of the  major 
scale and uses all the same notes as the major scale.

* Chords
** Chord Basics
When we play a bunch of notes together, we're playing a *chord*. Play any notes from a given key 
and we're playing chords from that key. Chords have a strong relationship with the key of the 
music.

If you play 3 notes together, you're playing a type of chord called a *triad*,. These chords get a 
special name because they are very special chords. If you play the 1st, 3rd and 5th degrees
together you are playing a *major chord* or *major triad*. So now you instantly know all the major 
triads.
#+ATTR_HTML: :border 0 :rules all :frame none
  | Degree   | C\sharp / D\flat | G\sharp / A\flat | D\sharp / E\flat | A\sharp / B\flat | F | C | G | D       | A       | E       | B       | F\sharp / G\flat |
  |----------+------------------+------------------+------------------+------------------+---+---+---+---------+---------+---------+---------+---------|
  | root     | D\flat           | A\flat           | E\flat           | B\flat           | F | C | G | D       | A       | E       | B       | F\sharp |
  | skip one |                  |                  |                  |                  |   |   |   |         |         |         |         |         |
  | 3rd      | F                | C                | G                | D                | A | E | B | F\sharp | C\sharp | G\sharp | D\sharp | A\sharp |
  | skip one |                  |                  |                  |                  |   |   |   |         |         |         |         |         |
  | 5th      | A\flat           | E\flat           | B\flat           | F                | C | G | D | A       | E       | B       | F\sharp | C\sharp |

** Important traids
Notice the pattern is play one, skip one, play one, skip one, play one. For example in C Major
the notes are CDEFGAB and the C Major Triad is CEG skipping D and F. You can move this pattern 
around and get a bunch of other triads. Using this same pattern, we can start on each degree of a
scale. We like to give them numbers too and use upper and lower case, the case is important too.
#+ATTR_HTML: :border 0 :rules all :frame none
  | Chord     | I     | ii    | iii   | IV    | V     | vi     | vii    |
  |-----------+-------+-------+-------+-------+-------+--------+--------|
  | Intervals | 1,3,5 | 2,4,6 | 3,5,7 | 4,6,1 | 5,7,2 | 6,1,3  | 7,2,4  |
  | or        | 1,3,5 | 2,4,6 | 3,5,7 | 4,6,8 | 5,7,9 | 6,8,10 | 7,9,11 |
Let's look at these in a different way. What is the interval from 1st to 3rd? Using TTSTTTS we 
can see it's two tones and from 3rd to 5th is a semitone plus a tone. Sometimes this might be 
explained as 4 semitones then 3 semitones. This 4+3 is the pattern for a major chord.
#+ATTR_HTML: :border 0 :rules all :frame none
  | Chord        | I     | ii    | iii   | IV    | V     | vi    | vii   |
  |--------------+-------+-------+-------+-------+-------+-------+-------|
  | Intervals    | 1,3,5 | 2,4,6 | 3,5,7 | 4,6,1 | 5,7,2 | 6,1,3 | 7,2,4 |
  | In semitones | 4 + 3 | 3 + 4 | 3 + 4 | 4 + 3 | 4 + 3 | 3 + 4 | 3 + 3 |
We can see all the uppercase ones are 4+3, major chords. All except one of the lowercase ones are 
3+4, which is the pattern for a *minor chord*. The odd one out is vii. It is 3+3 and called a 
*diminished chord*. Yeah it's the runt of the family and we'll ignore it for now. 
I find it quite lovely that we have the 4+3 and 3+4 for major and minor chords. It blows my mind 
that people figured this stuff out and came up with such an elegant language of music.

** Traids in every key
Major chords are generally just be denoted by the root note, so C Major will be written C. Minor 
chords will have the root note plus a small m, so A Minor is written Am. Flats and sharps are put 
in their proper place after the note name. Here again we can see why we want to keep the notes 
in each key labeled as ABCDEFG and use \flat and \sharp to do so. Things would get very confusing 
indeed.
#+ATTR_HTML: :border 0 :rules all :frame none
  | Key     | I       | ii         | iii        | IV     | V       | vi         |
  |---------+---------+------------+------------+--------+---------+------------|
  | D\flat  | D\flat  | E\flat{}m  | Fm         | G\flat | A\flat  | B\flat{}m  |
  | A\flat  | A\flat  | B\flat{}m  | C          | D\flat | E\flat  | Fm         |
  | E\flat  | E\flat  | Fm         | Gm         | A\flat | B\flat  | Cm         |
  | B\flat  | B\flat  | Cm         | Dm         | E\flat | F       | Gm         |
  | F       | F       | Gm         | Am         | B\flat | C       | Dm         |
  | C       | C       | Dm         | Em         | F      | G       | Am         |
  | G       | G       | Am         | Bm         | C      | D       | Em         |
  | D       | D       | Em         | F\sharp{}m | G      | A       | Bm         |
  | A       | A       | Bm         | C\sharp{}m | D      | E       | F\sharp{}m |
  | E       | E       | F\sharp{}m | G\sharp{}m | A      | B       | C\sharp{}m |
  | B       | B       | C\sharp{}m | D\sharp{}m | E      | F\sharp | G\sharp{}m |
  | F\sharp | F\sharp | G\sharp{}m | A\sharp{}m | B      | C\sharp | D\sharp{}m |

* Pieces of music and songs
** Chord progressions
*** TODO progression usage
*** TODO commonly used progressions

** Chord Inversions
*** TODO inversion usage

** Melodies
*** TODO melodies

* Appendix
** Various scales
** TODO document various scales
- Chromatic:
  If you play the 12 semitones, say by going up a guitar string, fret by fret, or by playing each 
  note (white and black) on a piano.
#+ATTR_HTML: :border 0 :rules all :frame none
  | pattern   | S | S | S | S | S | S | S | S | S | S | S | S |
  | semitones | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |
- Major:
#+ATTR_HTML: :border 0 :rules all :frame none
  | pattern   | T | T | S | T | T | T | S |
  | semitones | 2 | 2 | 1 | 2 | 2 | 2 | 1 |
  | Interval  | 1 | 2 | 3 | 4 | 5 | 6 | 7 |
- Minor scale:
#+ATTR_HTML: :border 0 :rules all :frame none
  | pattern   | T | S | T  | T | S | T  | T  |
  | semitones | 2 | 1 | 2  | 2 | 1 | 2  | 2  |
  | Interval  | 1 | 2 | b3 | 4 | 5 | b6 | b7 |
- Pentatonic scales:
  Some poeople provide a pattern for pentatonic scales but I prefer to think about them
  as selecting 5 notes (penta) from the Major or Minor scale.
-- from the Major scale include 1, 2, 3, 5, 6 or skip the 4th and 7th
#+ATTR_HTML: :border 0 :rules all :frame none
  | semitones | 2 | 2 | 1 | 2 | 2 | 2 | 1 |
  | Interval  | 1 | 2 | 3 | 4 | 5 | 6 | 7 |
  | Include?  | 1 | 2 | 3 | X | 5 | 6 | X |
-- from the Minor scale include 1, b3, 4, 5, b7 or exclude the 2nd and flat 6th
#+ATTR_HTML: :border 0 :rules all :frame none
  | semitones | 2 | 1 | 2  | 2 | 1 | 2  | 2  |
  | Interval  | 1 | 2 | b3 | 4 | 5 | b6 | b7 |
  | Include?  | 1 | X | b3 | 4 | 5 | X  | b7 |


* Useful links
- Piano Exercises: https://pianoexercises.org recommended to me was https://pianoexercises.org/exercises/czerny/
- Various musical transcriptions: https://imslp.org
- Chordmaps, music theory and chordmaps midi app: https://www.mugglinworks.com/
- An instrument supplier who will ship to HK cheaper than buying locally https://www.thomann.de
- https://www.musictheory.net
- I think Andrew Huang's music theory in 1/2 hr is one of the 
  easiest run-through's of music theory https://www.youtube.com/watch?v=rgaTLrZGlk0
  Note, you should do the exercises and it's not half an hour, it's weeks of work if
  you take learning music theory seriously. Tip: Play it at 1.5x
- Some really insightful analysis of chord progressions and melodic overlays from the 80's
  https://www.youtube.com/watch?v=jav5xMqBWeY
- Piano scales and their fingerings: https://www.pianoscales.org

